services:
  customer-service:
    image: "hkapilkumar/customer-service:s4"
    container_name: cs-container
    ports:
      - "9080:9080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - kpservice

  product-service:
    image: "hkapilkumar/product-service:s4"
    container_name: ps-container
    ports:
      - "9081:9081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - kpservice
networks:
  kpservice:
    driver: "bridge"


#To run docker compose
# docker compose up -d
# docker compose down
# docker compose start
# docker compose stop